apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: printed-cockroach-java-quarkus
  janus-idp.io/tekton: printed-cockroach-java-quarkus
  backstage.io/kubernetes-id: printed-cockroach-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: printed-cockroach-java-quarkus
resources: 
- deployment.yaml
- route.yaml
- service.yaml
